Repository LemLib/LemLib, pull requests merged in 2023-03, with the labels that each got.

#29 [Feature] Community Features
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/lemlib.md
Labels: feature request

#31 Style Guide
  .clang-format
  .github/CONTRIBUTING.md
  .github/workflows/test-clang-format.yml
  include/lemlib/api.hpp
  include/lemlib/chassis/chassis.hpp
  include/lemlib/chassis/odom.hpp
  include/lemlib/chassis/trackingWheel.hpp
  include/lemlib/logger.hpp
  include/lemlib/pid.hpp
  include/lemlib/pose.hpp
  include/lemlib/util.hpp
  src/lemlib/chassis/chassis.cpp
  src/lemlib/chassis/odom.cpp
  src/lemlib/chassis/pursuit.cpp
  src/lemlib/chassis/trackingWheel.cpp
  src/lemlib/logger.cpp
  src/lemlib/pid.cpp
  src/lemlib/pose.cpp
  src/lemlib/util.cpp
  src/main.cpp
Labels: enhancement

#33 add optional encoder gear ratio
  include/lemlib/chassis/trackingWheel.hpp
  src/lemlib/chassis/trackingWheel.cpp
Labels: confirmed bug, enhancement
